name: build-frontend
on:
  push:
    paths:
      - 'apps/frontend/**'
      - 'package.json'
      - 'package-lock.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run --workspace apps/frontend export
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-out
          path: apps/frontend/out
